[project]
name = 'docs'
channels = ['conda-forge']
platforms = ['linux-64', 'osx-arm64', 'osx-64', 'win-64']

[dependencies]
htmlmin = '>=0.1.12'
jsmin = '>=3.0.1'
mdx_truly_sane_lists = '>=1.3.0'
mkdocs = '>=1.5.0'
mkdocs-macros-plugin = '>=1.0.0'
mkdocs-material = '>=8.5.0'
python = '<3.13.0a0'

[pypi-dependencies]
mkdocs-minify-plugin = '==0.6.3'

[pypi-options]
index-url = 'https://mirrors.cernet.edu.cn/pypi/web/simple'
