site_name: Google Style Guides

theme:
  name: material
  features:
  - header.autohide
  - navigation.tabs
  - navigation.top
  - toc.follow
  - toc.integrate

nav:
- AngularJS: angularjs-google-style.html
- Common Lisp: lispguide.xml
- C++: cppguide.html
- C#: csharp-style.md
- Go:
  - Overview: go/index.md
  - go/guide.md
  - go/decisions.md
  - go/best-practices.md
- HTML/CSS: htmlcssguide.html
- JavaScript: jsguide.html
- Java: javaguide.html
- JSON: jsoncstyleguide.xml
- Markdown:
  - Overview: docguide/README.md
  - docguide/style.md
  - docguide/best_practices.md
  - docguide/READMEs.md
  - docguide/philosophy.md
- Objective-C: objcguide.md
- Python: pyguide.md
- R: Rguide.md
- Shell: shellguide.md
- TypeScript: tsguide.html
- Vim: vimscriptguide.xml

exclude_docs: |
  /CODE_OF_CONDUCT.md

not_in_nav: |
  /README.md

plugins:
- macros
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
    cache_safe: true

markdown_extensions:
- def_list
- footnotes
- md_in_html
- pymdownx.highlight:
    anchor_linenums: true
    linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tilde
- toc:
    permalink: true
    toc_depth: 4

validation:
  links:
    unrecognized_links: ignore
