site_name: C++ Core Guidelines

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.top
  - toc.follow
  - toc.integrate

nav:
- README.md
- Contents: CppCoreGuidelines.md
- FAQ: docs/gsl-intro.md
- Talks: talks/README.md

exclude_docs: |
  /index.html
  /SECURITY.md

not_in_nav: |
  /CONTRIBUTING.md

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- toc:
    baselevel: 2
    toc_depth: 4
